spring.application.name=liquor


spring.datasource.url={DB_URL}
spring.datasource.username={DB_USERNAME}
spring.datasource.password={DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


razorpay.key-id=${razorpay_key_id}

razorpay.key-secret=${razorpay_key_secret}

app.frontend-url=http://localhost:5173
